language: rust
os:
  - linux
  - osx
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; else sudo apt-get update; fi
install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install openal-soft libsndfile; else sudo apt-get install libopenal-dev libsndfile1-dev; fi
env:
 - RUST_TEST_TASKS=1
script:
  - rustc --version
  - cargo build
  - cargo doc
