language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
os:
  - linux
  - osx
before_install:
  - [ $TRAVIS_OS_NAME = osx ] && brew update
install:
  - [ $TRAVIS_OS_NAME = osx ] && brew install openal-soft libsndfile
addons:
  apt:
    packages:
      - libopenal-dev
      - libsndfile1-dev
script:
  - cargo build
after_success:
  - |
  [ $TRAVIS_BRANCH = master ] &&
  [ $TRAVIS_PULL_REQUEST = false ] &&
  [ $TRAVIS_RUST_VERSION = stable ] &&
  cargo doc &&
  npm install gitbook-cli -g &&
  gitbook build ./book &&
  mv ./book/_book ./target/doc/book &&
  git clone https://github.com/davisp/ghp-import &&
  ./ghp-import/ghp-import target/doc &&
  git push -fq https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages
