language: rust
rust:
- stable
- beta
- nightly
matrix:
  allow_failures:
  - rust: nightly
os:
- linux
- osx
install:
- |
  [ $TRAVIS_OS_NAME = linux ] || brew install openal-soft libsndfile
addons:
  apt:
    packages:
    - libopenal-dev
    - libsndfile1-dev
script:
- cargo test
