env:
  global:
    - secure: VnbCoVYdkLNGJsF7QXsu+fGVK1YkPmxvx3YuG5gQaUM+OkinME7hAlnUkDwwxet8G9U2ZX/nRo3XFUhC9yHGBL//bv++hOoLkGgqjhq5BFDBsiwVoEwuLcLr69xxa+4nn20zdG+ZTbz0tvxc05uz4ItZ2q+0oByMdhyqJT4PJzA=
before_install:
  - yes | sudo add-apt-repository ppa:hansjorg/rust
  - sudo apt-get update
install:
  - sudo apt-get install rust-nightly
  - sudo apt-get install libopenal-dev
  - sudo apt-get install libsndfile1-dev
#env:
#  - RUST_TEST_TASKS=1
script:
  - rustc src/ears/lib.rs
#  - rustc --test src/ears/lib.rs  -o bin/ears_tests
#  - cd bin 
#  - ./ears_tests
  - rustdoc -o doc src/ears/lib.rs
after_script:
  - curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh