language: rust
matrix:
  include:
    - os: linux
      rust: stable
    - os: linux
      rust: beta
    - os: linux
      rust: nightly
  allow_failures:
  - rust: nightly
install:
- |
  [ $TRAVIS_OS_NAME = linux ] || brew install openal-soft libsndfile
addons:
  apt:
    packages:
    - libopenal-dev
    - libsndfile1-dev
script:
- cargo test
