[package]
name = "ears"
version = "0.3.1"
authors = ["Jeremy Letang <letang.jeremy@gmail.com>", "Jan Niklas Hasse <jhasse@bixense.com>"]
license = "MIT"
keywords = ["audio", "openal", "sndfile"]
readme = "README.md"
build = "build.rs"

repository = "https://github.com/jhasse/ears"
documentation = "http://bixense.com/ears/ears/"
description = "Easy Api in Rust to play Sounds"

[lib]
name = "ears"
crate-type = ["dylib", "rlib"]

[dependencies]
libc = "*"
